# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
- job: terraform_deployment
  pool:
    vmImage: ubuntu-latest
  variables:
    az_region: eastus
    resource_group_name: JessAKSCICD
    subscription: 5db7a2e4-25f1-4c0d-a100-d13e44d1f64f
    key_vault_name: jesskeyvault1
    sa_prefix: AksTerraformSPN
    sa_container_name: jesscont
    tfstateFile: terraform.tfstate

  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: '5db7a2e4-25f1-4c0d-a100-d13e44d1f64f' #replace with your service connection - azure resource manager service principal
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az group create -n $(resource_group_name) -l $(az_region)
        VAULT_ID=$(az keyvault create --name "$(key_vault_name)" --resource-group "$(resource_group_name)" --location "$(az_region)" --query "id" -o tsv)
        az storage account create --resource-group $(resource_group_name) --name "$(sa_prefix)" --sku Standard_LRS --encryption-services blob
        az storage container create --name $(sa_container_name) --account-name "$(sa_prefix)" --auth-mode login
  - task: TerraformInstaller@0
    displayName: Terraform Installation
    inputs:
      terraformVersion: 'latest'
  - task: TerraformTaskV3@3
    displayName: Terraform Init
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/tf-files'
      backendServiceArm: 'AKSSvcconn'
      backendAzureRmResourceGroupName: '$(resource_group_name)'
      backendAzureRmStorageAccountName: '$(sa_prefix)'
      backendAzureRmContainerName: '$(sa_container_name)'
      backendAzureRmKey: '$(tfstateFile)'

  - task: TerraformTaskV3@3
    displayName: Terraform Plan
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/tf-files'
      commandOptions: '-out=tfplan'
      environmentServiceNameAzureRM: 'akrish-poc-sp'

  - task: TerraformTaskV3@3
    displayName: Terraform Apply
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/tf-files'
      commandOptions: 'tfplan'
      environmentServiceNameAzureRM: 'AKSSvcconn'